### ISSUE TITLE
Alarm logger "server.port" setting is not taken into account

### ISSUE THREAD

**Issue by lcaouen** [epics-extensions/EPNix#56]
The server.port setting is not taken into account.
```
  services.phoebus-alarm-logger = {
    settings = {
      "server.port" = 8082;
    };
  };
```
I tried to use my own application.properties, a java 16 version, my own ajarm-logger.jar, but the port was always 8080.
However from time to time the port was taken into account but then I could not reproduce it.

The only way to change the port is to use a java parameter -Dserver.port=8082

**Comment by stephane-cea** [comment]
I'm also encountering the exact same issue

**Comment by stephane-cea** [comment]
Like said by @lcaouen, a nice workaround is to use: 
```
systemd.services.phoebus-alarm-logger.environment.JAVA_OPTS = lib.mkForce "-Djava.util.prefs.userRoot=/var/lib/phoebus-alarm-logger -Dserver.port=8082";
```

(thanks @minijackson for the Nix syntax)

**Comment by minijackson** [comment]
Okay, so I think I've figured out what's happening.

phoebus-alarm-logger doesn't set the configuration properties of SpringBoot at all. For any `.properties` file passed to phoebus-alarm-server with the  `-properties` argument, it will *not* set any of the properties of SpringBoot, like `server.port`.

*However*, after reading the [External Configuration](https://docs.spring.io/spring-boot/reference/features/external-config.html) SpringBoot documentation, I found this bit:

> Config data (such as application.properties files).

> 3. [Application properties](https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.files) outside of your packaged jar (application.properties and YAML variants).

> Spring Boot will automatically find and load `application.properties`
> and `application.yaml` files from the following locations when your
> application starts:
>
> 1.  From the classpath
>     a.  The classpath root
>     b.  The classpath `/config` package
> 2.  From the current directory
>     a.  The current directory
>     b.  The `config/` subdirectory in the current directory
>     c.  Immediate child directories of the `config/` subdirectory

And our documentation about phoebus-alarm-server suggest to name the properties file `application.properties`, and run `./alarm-logger.sh -properties ./application.properties -noshell`

This means that by luck, SpringBoot was also loading `application.properties` in the current directory, by virtue of being named that way.

I think that in reality, there is two different properties files: one for phoebus-alarm-logger, and one for SpringBoot. But since there's low chance of options collision, I think we can keep it as a single file.

To fix the issue, we can set the command-line for starting phoebus-alarm-logger to be:

```bash
export SPRING_CONFIG_IMPORT=/path/to/alarm-logger.properties
phoebus-alarm-logger -properties /path/to/alarm-logger.properties
```

That way, both phoebus-alarm-server and SpringBoot load the same config file.
