### ISSUE TITLE
The creation of a testApp / ioctest is problematic

### ISSUE THREAD

**Issue by agaget** [epics-extensions/EPNix#64]
the word `test` is reserved by bash (or maybe other stuff) and the nix build with such a name provok some weird behaviour. The last one is that the shebang of the `st.cmd` was changed to a wrong one.

We need to get a message or an error if we are using such a name and maybe there is other word reserved that cause problem ?

**Comment by minijackson** [comment]
Ok, so what happens is, Nix tries to be friendly and hardcode programs that it finds in the `#!/.../.../shebang/program` of scripts.

And, for those executable, it uses `command -v program` to see where the program is in the `$PATH`.

But, `test` is a Bash builtin, and so `command -v test` just returns `test` instead of a path to an executable.

I'm going to open a PR to see if we can replace that with `type -P program`, which should have the correct behavior. But note that this is going to cause a massive rebuild, since that logic is enabled by default in basically every nixpkgs package.

An other solution we might look, is to set `dontPatchShebangs = true;` by default for EPICS IOCs, which should be fine since we don't have non-cmd scripts, but this *might* surprise us in the future.

**Comment by minijackson** [comment]
PR opened: NixOS/nixpkgs#330188

**Comment by agaget** [comment]
Thanks! in the meantime I've stopped naming my App test and more example :)

**Comment by minijackson** [comment]
PR was merged, so it should be fixed when NixOS 24.11 releases
